/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationSummary {
  'id' : bigint,
  'title' : string,
  'updatedAtNs' : bigint,
  'messageCount' : bigint,
}
export interface Credentials {
  'expiresAt' : string,
  'baseUrl' : string,
  'apiKey' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface MessagePage {
  'total' : bigint,
  'messages' : Array<StoredMessage>,
  'summary' : [] | [Summary],
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export interface StoredMessage {
  'content' : string,
  'role' : { 'user' : null } |
    { 'assistant' : null },
  'createdAtNs' : bigint,
}
export interface Summary {
  'content' : string,
  'createdAtNs' : bigint,
  'coversCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteConversation' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationPage' : ActorMethod<[bigint, bigint], MessagePage>,
  'getInferenceCredentials' : ActorMethod<[], Credentials>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isInferenceConfigured' : ActorMethod<[], boolean>,
  'listConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'probeEphemeralMint' : ActorMethod<
    [],
    { 'expiresAt' : string, 'last4' : string }
  >,
  'recordExchange' : ActorMethod<[[] | [bigint], string, string], bigint>,
  'setConversationSummary' : ActorMethod<[bigint, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];