/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StoredMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  'createdAtNs' : IDL.Int,
});
export const Summary = IDL.Record({
  'content' : IDL.Text,
  'createdAtNs' : IDL.Int,
  'coversCount' : IDL.Nat,
});
export const MessagePage = IDL.Record({
  'total' : IDL.Nat,
  'messages' : IDL.Vec(StoredMessage),
  'summary' : IDL.Opt(Summary),
});
export const Credentials = IDL.Record({
  'expiresAt' : IDL.Text,
  'baseUrl' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const ConversationSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'updatedAtNs' : IDL.Int,
  'messageCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteConversation' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationPage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MessagePage],
      ['query'],
    ),
  'getInferenceCredentials' : IDL.Func([], [Credentials], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInferenceConfigured' : IDL.Func([], [IDL.Bool], []),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'probeEphemeralMint' : IDL.Func(
      [],
      [IDL.Record({ 'expiresAt' : IDL.Text, 'last4' : IDL.Text })],
      [],
    ),
  'recordExchange' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'setConversationSummary' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StoredMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
    'createdAtNs' : IDL.Int,
  });
  const Summary = IDL.Record({
    'content' : IDL.Text,
    'createdAtNs' : IDL.Int,
    'coversCount' : IDL.Nat,
  });
  const MessagePage = IDL.Record({
    'total' : IDL.Nat,
    'messages' : IDL.Vec(StoredMessage),
    'summary' : IDL.Opt(Summary),
  });
  const Credentials = IDL.Record({
    'expiresAt' : IDL.Text,
    'baseUrl' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const ConversationSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'updatedAtNs' : IDL.Int,
    'messageCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteConversation' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationPage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MessagePage],
        ['query'],
      ),
    'getInferenceCredentials' : IDL.Func([], [Credentials], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInferenceConfigured' : IDL.Func([], [IDL.Bool], []),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'probeEphemeralMint' : IDL.Func(
        [],
        [IDL.Record({ 'expiresAt' : IDL.Text, 'last4' : IDL.Text })],
        [],
      ),
    'recordExchange' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'setConversationSummary' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };